import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const BYekan = localFont({
	src: [
		{
			path: "../../public/fonts/BYekan+.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../public/fonts/BYekan+ Bold.ttf",
			weight: "700",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${BYekan.className} h-full antialiased`}>
			<body className="min-h-full flex flex-col justify-start items-center bg-[#060708]">
				<div className="max-w-78">{children}</div>
			</body>
		</html>
	);
}
